### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/video-call-landing-page#5]

**Comment by Frijol** [comment]
I assume we want the favicon to match the one at https://envirodatagov.org/

This would be a good issue for a good-first-issue label!

**Comment by patcon** [comment]
Great idea @Frijol! These links might be helpful for someone who jumps on this issue :)

- StackOverflow: [How to serve static files in Flask](https://stackoverflow.com/a/20648053/504018) (flask is the framework we use for this small `app.py` 🎉 )
- StackOverflow: [Adding a favicon to a static HTML page](https://stackoverflow.com/a/9943801/504018)
